version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samlambdastackapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-161vf2psfddwi"
s3_prefix = "samlambdastackapp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
